### Numpy Arrays

In [92]:
#creating a list
my_list = [1,2,3]

In [93]:
import numpy as np


In [94]:
#converting the normal list to numpy array
arr = np.array(my_list)

In [95]:
arr



array([1, 2, 3])

In [96]:
#creating a list of list, them converting it will create 2dimentional numpy array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [97]:
#creating 2D numpy array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#np.arange(start,stop,step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [99]:
#create a numpy array of zeros
np.zeros(3)

array([0., 0., 0.])

In [100]:
#passinga tuple to zeros will create 2D array of zeros (rows,columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
# 1 dimensional array of ones
np.ones(3)

array([1., 1., 1.])

In [102]:
# 2 dimensional array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
# np.linspace(start,stop,num)
np.linspace(0,10,5) #will create 5 numbers between 0 and 10 equally spaced

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [104]:
#identitu matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
#creating a random array of given shape, picking numbers from a uniform distribution over [0,1)
np.random.rand(5)  #will create 5 random numbers between 0 and 1, creating 1D array

array([0.22270452, 0.7494126 , 0.56289224, 0.29646295, 0.29513178])

In [106]:
#creating 2D array 
np.random.rand(4,3)  #will create 4*3 random numbers between 0 and 1, creating 2D array

array([[0.86791214, 0.74716523, 0.48253188],
       [0.18907191, 0.7337555 , 0.087522  ],
       [0.97013235, 0.20724676, 0.23872758],
       [0.80050499, 0.99263438, 0.83087797]])

In [107]:
# creating random from standard normal distribution
np.random.randn(5)  #will create 5 random numbers from standard normal distribution, creating 1D array

array([-0.59860071, -1.18114809, -2.05675778, -1.34950579, -0.33800404])

In [108]:
np.random.randn(4,4)

array([[ 1.77529973,  1.17031519, -1.05090371,  0.28220058],
       [ 0.0581642 , -0.81854638, -0.41960941, -0.5497849 ],
       [-0.30704987, -0.3130308 , -0.9021109 ,  0.23078113],
       [-0.03451415,  0.45384084,  0.64500983, -0.84075808]])

In [109]:
#np.random.randint(low, high)
np.random.randint(1,100)

24

In [110]:
np.random.randint(1,100,5)  #will create 5 random integers between 1 and 100

array([25, 94, 57, 37, 59], dtype=int32)

In [111]:
arr = np.arange(10)

In [112]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
ranarr = np.random.randint(0,50,10)

In [114]:
ranarr

array([ 1, 38, 15, 47,  3, 38, 13,  4, 40, 12], dtype=int32)

In [115]:
arr.shape

(10,)

In [116]:
#reshaping the array
arr.reshape(2,5) #these new shape when multiplied should be equal to total number of element in array, 2*5 =10


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
ranarr

array([ 1, 38, 15, 47,  3, 38, 13,  4, 40, 12], dtype=int32)

In [118]:
ranarr.max()

np.int32(47)

In [119]:
ranarr.min()

np.int32(1)

In [120]:
#finding the index of max or min value by argmax() and argmin()
ranarr.argmax()  #index of max value

np.int64(3)

In [121]:
ranarr.argmin()

np.int64(0)

In [122]:
#showing the data type of array
arr.dtype

dtype('int64')

In [123]:
#showing the shape of array
arr.shape

(10,)

### Numpy indexing and selection

In [124]:
arr = np.arange(0, 11)

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr[0] #indexing starts from 0, so this will give first element of array

np.int64(0)

In [127]:
#slicing
arr[1:5] #will give elements from index 1 to 4, last index is exclusive

array([1, 2, 3, 4])

In [128]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [129]:
#starting from start and going upto specific index
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [130]:
arr[3:] #starting from specific index and going upto end of array

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting

In [131]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr [0:5] = 100 #will change the value of index 0 to 4 to 100

In [133]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [134]:
#resetting the array to original
arr = np.arange(0, 11)

In [135]:
#creating a slice from the actual array
slice_of_arr = arr[0:6]

#show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [136]:
#modifying the slice
slice_of_arr[:] = 99
#showing the slice after modification
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [137]:
#changes are also occuring in the main array because slice_of_arr is just a view of arr, not a copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [138]:
#to make a copy of array we can use copy() method
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [139]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [140]:
arr  #the main array is not affected,when copy is used

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array
The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. 

In [141]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
#indexing row
arr_2d[0] #accessing first row

array([1, 2, 3])

In [143]:
#accessin element using double bracket [row][colmn]
arr_2d[0][1] #accessing second element of first row

np.int64(2)

In [144]:
#accessing format [row,colmn]
arr_2d[0,1]

np.int64(2)

In [145]:
arr_2d[2,2]

np.int64(9)

In [146]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
#2D array slicing
arr_2d[:2,1:]  #for row taking row 0 and 1, for column taking col 1 and 2

array([[2, 3],
       [5, 6]])

In [152]:
arr_2d[:2] #taking first two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
#conditional selection
bool_arr = arr > 5

In [156]:
#selecting
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [157]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr

In [160]:
arr_2d = np.arange(50).reshape(5,10)

In [161]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [162]:
arr_2d[1,3:5]

array([13, 14])

# NumPy Operations

In [163]:
arr = np.arange(0,11)

In [164]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [165]:
arr + arr #element wise addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [166]:
arr - arr #element wise subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [167]:
arr * arr #element wise multiplication  

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [168]:
# operation with a single element is also broadcasted to all element in array
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [169]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
# 0 / 0 is not defined, so it will give nan (not a number)
arr  /  arr

C:\Users\yeasi\AppData\Local\Temp\ipykernel_16872\3859460317.py:1: RuntimeWarning: invalid value encountered in divide
  arr  /  arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [173]:
# 1 / 0 will show inf (infinity)
1 / arr 

C:\Users\yeasi\AppData\Local\Temp\ipykernel_16872\1927252527.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
#power of numpy array
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [175]:
#square root of numpy array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [176]:
#exponential of numpy array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [177]:
#max of numpy array
np.max(arr)

np.int64(10)

In [178]:
arr.max()

np.int64(10)

In [179]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [180]:
np.log(arr)

C:\Users\yeasi\AppData\Local\Temp\ipykernel_16872\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])